name: LangPort GitHub Actions for Development
run-name: LangPort GitHub Actions for Development
on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Apache Arrow
        run: |
          wget https://dist.apache.org/repos/dist/dev/arrow/KEYS 
          apt-key add < KEYS
          DISTRO=$(lsb_release --codename --short)
          add-apt-repository "deb [arch=amd64] http://dl.bintray.com/apache/arrow/ubuntu $DISTRO main"
          apt-get install libarrow-dev libparquet-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install LangPort
        run: |
          cd ${{ github.workspace }}
          pip install --upgrade pip
          pip install -e .

      - name: Test LangPort
        run: |
          cd ${{ github.workspace }}
          python -m unittest discover langport/tests
